FROM scratch

LABEL maintainer="Liquidaty"
LABEL url="https://github.com/liquidaty/zsv"
LABEL org.opencontainers.image.description="zsv: tabular data swiss-army knife CLI + world's fastest (simd) CSV parser"

WORKDIR /zsv
COPY ci/zsv .

ENTRYPOINT [ "./zsv" ]
